use clap::{App, Arg, ArgMatches, SubCommand};

pub fn get_matches<'a>() -> ArgMatches<'a> {
    App::new("Redmine Remote")
        .version("0.0.1")
        .author("Florian Sommer <fsommer1986@gmail.com>")
        .about("Command line program for using the redmine api (see http://www.redmine.org/).")
        .arg(Arg::with_name("host")
             .long("host")
             .takes_value(true))
        .arg(Arg::with_name("apikey")
             .long("apikey")
             .takes_value(true))
        .subcommand(SubCommand::with_name("issues")
                    .about("Handles the issues sub api.")
                    .subcommand(SubCommand::with_name("list")
                                .about("List issues."))
                    .subcommand(SubCommand::with_name("create")
                                .about("Creates new issue.")
                                .arg(Arg::with_name("set-project-id")
                                     .long("set-project-id")
                                     .takes_value(true)
                                     .help("Set project id."))
                                .arg(Arg::with_name("set-tracker-id")
                                     .long("set-tracker-id")
                                     .takes_value(true)
                                     .help("Set tracker id."))
                                .arg(Arg::with_name("set-status-id")
                                     .long("set-status-id")
                                     .takes_value(true)
                                     .help("Set status id."))
                                .arg(Arg::with_name("set-priority-id")
                                     .long("set-priority-id")
                                     .takes_value(true)
                                     .help("Set priority id."))
                                .arg(Arg::with_name("set-subject")
                                     .long("set-subject")
                                     .takes_value(true)
                                     .help("Set subject."))
                                .arg(Arg::with_name("set-description")
                                     .long("set-description")
                                     .takes_value(true)
                                     .help("Set description."))
                                .arg(Arg::with_name("set-category-id")
                                     .long("set-category-id")
                                     .takes_value(true)
                                     .help("Set category id."))
                                .arg(Arg::with_name("set-version-id")
                                     .long("set-version-id")
                                     .takes_value(true)
                                     .help("Set version id."))
                                .arg(Arg::with_name("set-assigned-to-id")
                                     .long("set-assigned-to-id")
                                     .takes_value(true)
                                     .help("Set assignet-to id."))
                                .arg(Arg::with_name("set-parent-issue-id")
                                     .long("set-parent-issue-id")
                                     .takes_value(true)
                                     .help("Set parent-issue id."))
                                .arg(Arg::with_name("set-watcher-user-ids")
                                     .long("set-watcher-user-ids")
                                     .takes_value(true)
                                     .help("Set watcher-user ids."))
                                .arg(Arg::with_name("set-is-private")
                                     .long("set-is-private")
                                     .takes_value(true)
                                     .help("Set private flag."))
                                .arg(Arg::with_name("set-estimated-hours")
                                     .long("set-estimated-hours")
                                     .takes_value(true)
                                     .help("Set estimated hours."))))
        .subcommand(SubCommand::with_name("time_entries")
                    .about("Handles the time entries sub api.")
                    .subcommand(SubCommand::with_name("create")
                                .about("Creates new time entry.")
                                .arg(Arg::with_name("issue-id")
                                     .required(true))
                                .arg(Arg::with_name("hours")
                                     .required(true))
                                .arg(Arg::with_name("activity-id")
                                     .required(true))
                                .arg(Arg::with_name("comments")
                                     .required(true))))
        .get_matches()
}
